install standard-test-roles on vagrant shim

diff --git a/VagrantfileTaskotronShim b/VagrantfileTaskotronShim
--- a/VagrantfileTaskotronShim
+++ b/VagrantfileTaskotronShim
@@ -110,6 +110,15 @@ Vagrant.configure("2") do |config|
         #install libtaskotron
         dnf install --best -y libtaskotron
 
+        dnf --enablerepo=updates-testing install --best -y  standard-test-roles 
+        if [ $? -ne 0 ]; then
+            dnf install --best -y standard-test-roles
+            if [ $? -ne 0 ]; then
+                echo "FAIL: Could not install standard-test-roles"
+                exit 1;
+            fi
+        fi
+
         git clone https://pagure.io/taskotron/task-standard-interface-shim.git
 
         #WORKAROUND PR#67
